// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·weakSumASM(SB), NOSPLIT, $0-28
	MOVQ block_base+0(FP), AX
	MOVQ block_len+8(FP), BX
	XORQ CX, CX
	XORQ DX, DX
	wsloop:
	TESTQ BX, BX
	JZ wsdone
	MOVBQZX (AX), SI
	ADDQ $31, SI
	ADDQ SI, CX
	ANDQ $0xFFFF, CX
	ADDQ CX, DX
	INCQ AX
	DECQ BX
	JMP wsloop
	wsdone:
	ANDQ $0xFFFF, DX
	SHLQ $16, DX
	ORQ CX, DX
	MOVL DX, ret+24(FP)
	RET

