// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·weakSumASM(SB), NOSPLIT, $0-28
	MOVD block_base+0(FP), R0
	MOVD block_len+8(FP), R1
	MOVD $0, R2
	MOVD $0, R3
	wsloop:
	CBZ R1, wsdone
	MOVBU (R0), R4
	ADD $31, R4, R4
	ADD R4, R2, R2
	AND $0xFFFF, R2, R2
	ADD R2, R3, R3
	ADD $1, R0, R0
	SUB $1, R1, R1
	JMP wsloop
	wsdone:
	AND $0xFFFF, R3, R3
	LSL $16, R3, R3
	ORR R2, R3, R3
	MOVW R3, ret+24(FP)
	RET

