//go:build arm64

package rdiff

// weakSumASM is the assembly implementation of the Rollsum weak checksum,
// generated by go-asmgen (see weaksum_asmgen.go) and implemented in
// weaksum_arm64.s. It must return the same value as WeakSum for every input.
func weakSumASM(block []byte) uint32
